---

# Airflow installation tasks

- name: 'Install native dependencies'
  become: true
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_config.dependencies.native }}"

- name: 'Create airflow user'
  become: true
  user:
    name: "{{ airflow_config.user.name }}"
    createhome: True
    home: "{{ airflow_config.user.path}}"
    state: 'present'
    shell: "{{ airflow_config.user.shell }}"

- name: 'Manage airflow user home directory permissions'
  become: true
  file:
    path: "{{ airflow_config.user.path }}"
    owner: "{{ airflow_config.user.name }}"
    group: "{{ airflow_config.user.group }}"
    mode: "{{ airflow_config.user.mode }}"

- name: 'Install airflow and python dependencies'
  become: true
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_config.environment.virtualenv }}"
    virtualenv_python: "{{ airflow_config.environment.python_version }}"
  with_items: "{{ airflow_config.dependencies.python }}"

- name: 'Install airflow modules'
  become: true
  pip:
    name: "{{ 'airflow[' + item.name + ']' }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_config.environment.virtualenv }}"
    virtualenv_python: "{{ airflow_config.environment.python_version }}"
  with_items: "{{ airflow_config.dependencies.modules }}"
