---

# Airflow configuration tasks

- name: 'Stat airflow config file'
  become: true
  stat:
    path: "{{ airflow_home_path }}/airflow.cfg"
  register: 'airflow_config_stat'
  changed_when: false

- name: 'Create airflow home directory'
  become: true
  file:
    path: "{{ airflow_home_path }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: "{{ airflow_home_mode }}"
    state: 'directory'

- name: 'Write airflow config file'
  become: true
  become_user: "{{ airflow_user_name }}"
  template:
    src: "{{ role_path }}/templates/airflow.cfg.j2"
    dest: "{{ airflow_home_path }}/airflow.cfg"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: '0400'
  notify: 'Restart airflow'

- name: 'Create airflow log folder'
  become: true
  file:
    path: "{{ airflow_log_path }}"
    owner: "{{ airflow_log_owner }}"
    group: "{{ airflow_log_group }}"
    mode: "{{ airflow_log_mode }}"
    state: 'directory'

- name: 'Create airflow pid folder'
  become: true
  file:
    path: "{{ airflow_pid_path }}"
    owner: "{{ airflow_pid_owner }}"
    group: "{{ airflow_pid_group }}"
    mode: "{{ airflow_pid_mode }}"
    state: 'directory'

- name: 'Configure airflow log rotation'
  become: true
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ airflow_logrotate_config }}"

- name: 'Initialize airflow database'
  become: true
  become_user: "{{ airflow_user_name }}"
  command: "{{ airflow_virtualenv }}/bin/airflow initdb"
  when:
    - "{{ not airflow_config_stat.stat.exists }}"
    - "{{ airflow_do_init_db }}"  # first run

- name: 'Upgrade airflow database'
  become: true
  become_user: "{{ airflow_user_name }}"
  command: "{{ airflow_virtualenv }}/bin/airflow upgradedb"
  when:
    - "{{ airflow_config_stat.stat.exists }}"
    - "{{ airflow_do_upgrade_db }}"  # first run

- name: 'Setting AIRFLOW_HOME in users profiles'
  become: true
  template:
    src: "{{ role_path }}/templates/profile.d/airflow.j2"
    dest: '/etc/profile.d/airflow'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
    - "{{ airflow_home_for_all_users }}"
    - "{{ airflow_do_upgrade_db }}"  # first run
