---

# Airflow installation tasks

- name: 'Install native dependencies'
  become: true
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_native_dependencies }}"

- name: 'Create airflow user'
  become: true
  user:
    name: "{{ airflow_user_name }}"
    createhome: True
    home: "{{ airflow_user_home_path}}"
    state: 'present'
    shell: "{{ airflow_user_shell }}"

- name: 'Manage airflow user home directory permissions'
  become: true
  file:
    path: "{{ airflow_user_home_path }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: "{{ airflow_user_home_mode }}"

- name: 'Install airflow and python dependencies'
  become: true
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
  with_items: "{{ airflow_packages }}"

- name: 'Install extra airflow packages'
  become: true
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
  with_items: "{{ airflow_extra_packages }}"
