---

# Airflow configuration tasks

- name: 'Create airflow home directory'
  become: true
  file:
    path: "{{ airflow_config.core.home }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: "{{ airflow_home_mode }}"
    state: 'directory'

- name: 'Create airflow DAG directory'
  become: true
  file:
    path: "{{ airflow_config.core.dags_folder }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: "{{ airflow_home_mode }}"
    state: 'directory'

- name: 'Create airflow plugins directory'
  become: true
  file:
    path: "{{ airflow_config.core.plugins_folder }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: "{{ airflow_home_mode }}"
    state: 'directory'

- name: 'Write airflow config file'
  become: true
  template:
    src: "{{ role_path }}/templates/airflow.cfg.j2"
    dest: "{{ airflow_home_path }}/airflow.cfg"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: '0400'
  notify: 'Restart airflow'

- name: 'Create airflow log folder'
  become: true
  file:
    path: "{{ airflow_log_path }}"
    owner: "{{ airflow_log_owner }}"
    group: "{{ airflow_log_group }}"
    mode: "{{ airflow_log_mode }}"
    state: 'directory'

- name: 'Create airflow pid folder'
  become: true
  file:
    path: "{{ airflow_pid_path }}"
    owner: "{{ airflow_pid_owner }}"
    group: "{{ airflow_pid_group }}"
    mode: "{{ airflow_pid_mode }}"
    state: 'directory'

- name: 'Configure airflow log rotation'
  become: true
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ airflow_logrotate_config }}"

- name: 'Initialize airflow database'
  become: true
  command: "{{ airflow_virtualenv }}/bin/airflow initdb"
  environment:
    AIRFLOW_HOME: "{{ airflow_home_path }}"
  when:
    - "{{ airflow_do_init_db }}"

- name: 'Upgrade airflow database'
  become: true
  command: "{{ airflow_virtualenv }}/bin/airflow upgradedb"
  environment:
    AIRFLOW_HOME: "{{ airflow_home_path }}"
  when:
    - "{{ airflow_do_upgrade_db }}"

- name: 'Setting AIRFLOW_HOME in users profiles'
  become: true
  template:
    src: "{{ role_path }}/templates/profile.d/airflow.j2"
    dest: '/etc/profile.d/airflow.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - "{{ airflow_home_for_all_users }}"

- name: 'Refreshing DAGs folder from git'
  become: true
  git:
    repo: "{{ airflow_git.repo }}"
    dest: "{{ airflow_config.core.dags_folder }}"
    version: "{{ airflow_git.version }}"
  when:
    - "{{ airflow_git.repo }}"
