---

# Airflow configuration tasks

- name: 'Create airflow home directory'
  become: true
  file:
    path: "{{ airflow_config.home.path }}"
    owner: "{{ airflow_config.home.owner }}"
    group: "{{ airflow_config.home.group }}"
    mode: "{{ airflow_config.home.mode }}"
    state: 'directory'

- name: 'Create airflow DAG directory'
  become: true
  file:
    path: "{{ airflow_config.core.dags_folder }}"
    owner: "{{ airflow_config.home.owner }}"
    group: "{{ airflow_config.home.group }}"
    mode: "{{ airflow_config.home.mode }}"
    state: 'directory'

- name: 'Create airflow plugins directory'
  become: true
  file:
    path: "{{ airflow_config.core.plugins_folder }}"
    owner: "{{ airflow_config.home.owner }}"
    group: "{{ airflow_config.home.group }}"
    mode: "{{ airflow_config.home.mode }}"
    state: 'directory'

- name: 'Write airflow config file'
  become: true
  template:
    src: "{{ role_path }}/templates/airflow.cfg.j2"
    dest: "{{ airflow_config.home.path }}/airflow.cfg"
    owner: "{{ airflow_config.home.owner }}"
    group: "{{ airflow_config.home.group }}"
    mode: '0400'
  notify: 'Restart airflow'

- name: 'Create airflow log folder'
  become: true
  file:
    path: "{{ airflow_config.log.path }}"
    owner: "{{ airflow_config.log.owner }}"
    group: "{{ airflow_config.log.group }}"
    mode: "{{ airflow_config.log.mode }}"
    state: 'directory'

- name: 'Create airflow pid folder'
  become: true
  file:
    path: "{{ airflow_config.pid.path }}"
    owner: "{{ airflow_config.pid.owner }}"
    group: "{{ airflow_config.pid.group }}"
    mode: "{{ airflow_config.pid.mode }}"
    state: 'directory'

- name: 'Configure airflow log rotation'
  become: true
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ airflow_config.log.rotation }}"

- name: 'Initialize airflow database'
  become: true
  command: "{{ airflow_config.environment.virtualenv }}/bin/airflow initdb"
  environment:
    AIRFLOW_HOME: "{{ airflow_config.home.path }}"
  when:
    - "{{ airflow_config.database.init }}"

- name: 'Upgrade airflow database'
  become: true
  command: "{{ airflow_config.environment.virtualenv }}/bin/airflow upgradedb"
  environment:
    AIRFLOW_HOME: "{{ airflow_config.home.path }}"
  when:
    - "{{ airflow_config.database.upgrade }}"

- name: 'Setting AIRFLOW_HOME in users profiles'
  become: true
  template:
    src: "{{ role_path }}/templates/profile.d/airflow.j2"
    dest: '/etc/profile.d/airflow.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - "{{ airflow_config.home.set_for_all_users }}"
