---

# Airflow services management

- name: 'Manage webserver service with upstart'
  become: true
  template:
    src: "{{ role_path }}/templates/upstart/airflow-webserver.conf.j2"
    dest: '/etc/init/airflow-webserver.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-webserver'
  when: "{{ 'airflow-scheduler' in airflow_managed_upstart_services }}"

- name: 'Manage webserver service with init.d'
  become: true
  template:
    src: "{{ role_path }}/templates/init.d/airflow-webserver.j2"
    dest: '/etc/init.d/airflow-webserver'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-webserver'
  when: "{{ 'airflow-scheduler' in airflow_managed_initd_services }}"

- name: 'Manage scheduler service with upstart'
  become: true
  template:
    src: "{{ role_path }}/templates/upstart/airflow-scheduler.conf.j2"
    dest: '/etc/init/airflow-scheduler.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-scheduler'
  when: "{{ 'airflow-scheduler' in airflow_managed_upstart_services }}"

- name: 'Manage scheduler service with init.d'
  become: true
  template:
    src: "{{ role_path }}/templates/init.d/airflow-scheduler.j2"
    dest: '/etc/init.d/airflow-scheduler'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-scheduler'
  when: "{{ 'airflow-scheduler' in airflow_managed_initd_services }}"

- name: 'Manage airflow services states'
  become: true
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ item.state }}"
  with_items: "{{ airflow_services_states }}"
