---

# Airflow services management

- name: 'Manage scheduler service with init.d'
  become: true
  template:
    src: "{{ role_path }}/templates/init.d/airflow-scheduler.j2"
    dest: '/etc/init.d/airflow-scheduler'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-scheduler'
  when: "{{ airflow_config.scheduler.sysinit == 'initd' }}"

- name: 'Manage scheduler service with upstart'
  become: true
  template:
    src: "{{ role_path }}/templates/upstart/airflow-scheduler.conf.j2"
    dest: '/etc/init/airflow-scheduler.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-scheduler'
  when: "{{ airflow_config.scheduler.sysinit == 'upstart' }}"

- name: 'Manage webserver service with init.d'
  become: true
  template:
    src: "{{ role_path }}/templates/init.d/airflow-webserver.j2"
    dest: '/etc/init.d/airflow-webserver'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-webserver'
  when: "{{ airflow_config.webserver.sysinit == 'initd' }}"

- name: 'Manage webserver service with upstart'
  become: true
  template:
    src: "{{ role_path }}/templates/upstart/airflow-webserver.conf.j2"
    dest: '/etc/init/airflow-webserver.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-webserver'
  when: "{{ airflow_config.webserver.sysinit == 'upstart' }}"

- name: 'Refreshing DAGs from git'
  become: false
  local_action:
    module: git
    repo: "{{ airflow_config.git.repo }}"
    dest: "{{ airflow_config.git.local_dest }}"
    version: "{{ airflow_config.git.version }}"
    key_file: "{{ airflow_config.git.key_file }}"
    accept_hostkey: "{{ airflow_config.git.accept_hostkey }}"
    force: "{{ airflow_config.git.force }}"
    ssh_opts: "{{ airflow_config.git.ssh_opts }}"
  when:
    - "{{ airflow_config.git.repo != None }}"

- name: 'Stopping services to deploy DAGs'
  become: true
  service:
    name: "{{ item.service_name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ 'stopped' }}"
  with_items: "{{ [airflow_config.scheduler, airflow_config.webserver] }}"
  when:
    - "{{ airflow_config.git.repo != None }}"

- name: 'Cleaning stale DAGs from host'
  become: true
  shell: "rm -rf {{ airflow_config.core.dags_folder ~ '/*' }}"
  when:
    - "{{ airflow_config.git.repo != None }}"

- name: 'Copying DAGs to host'
  become: true
  copy:
    src: "{{ airflow_config.git.local_dest ~ '/' }}"
    dest: "{{ airflow_config.core.dags_folder }}"
    owner: "{{ airflow_user.name }}"
  when:
    - "{{ airflow_config.git.repo != None }}"

- name: 'Cleanup temp DAG files'
  become: false
  local_action:
    module: file
    path: "{{ airflow_config.git.local_dest }}"
    state: absent
  when:
    - "{{ airflow_config.git.repo != None }}"

- name: 'Manage airflow services states'
  become: true
  service:
    name: "{{ item.service_name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ 'started' if item.enabled else 'stopped' }}"
  with_items: "{{ [airflow_config.scheduler, airflow_config.webserver] }}"
