---

# Handlers main file for airflow role

- name: 'Restart airflow'
  become: true
  service:
    name: "{{ item.service_name }}"
    state: 'restarted'
  with_items:
    - "{{ airflow_config.webserver }}"
    - "{{ airflow_config.scheduler }}"
  when: "{{ item.enabled == True }}"


- name: 'Restart airflow-webserver'
  become: true
  service:
    name: "{{ item.service_name }}"
    state: 'restarted'
  with_items:
    - "{{ airflow_config.webserver }}"
  when: "{{ item.enabled == True }}"


- name: 'Restart airflow-scheduler'
  become: true
  service:
    name: "{{ item.service_name }}"
    state: 'restarted'
  with_items:
    - "{{ airflow_config.scheduler }}"
  when: "{{ item.enabled == True }}"
