---

# Handlers main file for airflow role

- name: 'Restart airflow'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ [airflow_config.scheduler, airflow_config.webserver] }}"
  when: "{{ item.enabled == True }}"


- name: 'Restart airflow-webserver'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ [airflow_config.webserver] }}"
  when: "{{ item.enabled == True }}"


- name: 'Restart airflow-scheduler'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ [airflow_config.scheduler] }}"
  when: "{{ item.enabled == True }}"
